[package]
name = "apple-sys"
version = "0.2.0"
edition = "2021"
description = "The auto-managed -sys crate for Apple platforms using bindgen directly from build environment"
keywords = ["sys", "apple", "macos", "bindgen"]
categories = ["api-bindings", "os::macos-apis"]
authors = ["Jeong YunWon <jeong@youknowone.org>"]
repository = "https://github.com/youknowone/apple-sys/"
readme = "../README.md"
license = "BSD-2-Clause"
include = ["/src", "/*.rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apple-sys-macos = { git = "https://github.com/youknowone/apple-sys-prebuilt", tag = "macos-13.1.0", optional = true }
apple-sys-ios = { git = "https://github.com/youknowone/apple-sys-prebuilt", tag = "ios-16.2.0", optional = true }
# apple-sys-macos = { path = "../../apple-sys-prebuilt/macos", version = "*", optional = true }
# apple-sys-ios = { path = "../../apple-sys-prebuilt/ios", version = "*", optional = true }

objc = { version = "0.2.7", optional = true }

[build-dependencies]
apple-bindgen = { path = "../bindgen", version = "0.2.0", default-features = false, optional = true }

apple-sdk = "0.4.0"

[features]
default = ["objc", "prebuilt"]
prebuilt = ["apple-sys-macos", "apple-sys-ios"]
objc = ["dep:objc", "apple-sys-macos?/objc", "apple-sys-ios?/objc"]
bindgen = ["apple-bindgen"]
__allow_empty = []
__gen_prebuilt = ["bindgen"]  # dev-only feature

# AUTO-GENERATED: DO NOT ADD ANYTHING BELOW THIS LINE
AGL = ["apple-sys-macos?/AGL"]
ARKit = ["apple-sys-ios?/ARKit"]
AVFAudio = ["apple-sys-macos?/AVFAudio", "apple-sys-ios?/AVFAudio"]
AVFoundation = ["apple-sys-macos?/AVFoundation", "apple-sys-ios?/AVFoundation"]
AVKit = ["apple-sys-macos?/AVKit", "apple-sys-ios?/AVKit"]
AVRouting = ["apple-sys-macos?/AVRouting", "apple-sys-ios?/AVRouting"]
Accelerate = ["apple-sys-macos?/Accelerate", "apple-sys-ios?/Accelerate"]
Accessibility = ["apple-sys-macos?/Accessibility", "apple-sys-ios?/Accessibility"]
Accounts = ["apple-sys-macos?/Accounts", "apple-sys-ios?/Accounts"]
ActivityKit = ["apple-sys-ios?/ActivityKit"]
AdServices = ["apple-sys-macos?/AdServices", "apple-sys-ios?/AdServices"]
AdSupport = ["apple-sys-macos?/AdSupport", "apple-sys-ios?/AdSupport"]
AddressBook = ["apple-sys-macos?/AddressBook", "apple-sys-ios?/AddressBook"]
AddressBookUI = ["apple-sys-ios?/AddressBookUI"]
AppClip = ["apple-sys-ios?/AppClip"]
AppIntents = ["apple-sys-macos?/AppIntents", "apple-sys-ios?/AppIntents"]
AppKit = ["apple-sys-macos?/AppKit"]
AppTrackingTransparency = ["apple-sys-macos?/AppTrackingTransparency", "apple-sys-ios?/AppTrackingTransparency"]
AppleScriptKit = ["apple-sys-macos?/AppleScriptKit"]
AppleScriptObjC = ["apple-sys-macos?/AppleScriptObjC"]
ApplicationServices = ["apple-sys-macos?/ApplicationServices"]
AssetsLibrary = ["apple-sys-ios?/AssetsLibrary"]
AudioToolbox = ["apple-sys-macos?/AudioToolbox", "apple-sys-ios?/AudioToolbox"]
AudioUnit = ["apple-sys-macos?/AudioUnit", "apple-sys-ios?/AudioUnit"]
AudioVideoBridging = ["apple-sys-macos?/AudioVideoBridging"]
AuthenticationServices = ["apple-sys-macos?/AuthenticationServices", "apple-sys-ios?/AuthenticationServices"]
AutomaticAssessmentConfiguration = ["apple-sys-macos?/AutomaticAssessmentConfiguration", "apple-sys-ios?/AutomaticAssessmentConfiguration"]
Automator = ["apple-sys-macos?/Automator"]
BackgroundAssets = ["apple-sys-macos?/BackgroundAssets", "apple-sys-ios?/BackgroundAssets"]
BackgroundTasks = ["apple-sys-macos?/BackgroundTasks", "apple-sys-ios?/BackgroundTasks"]
BusinessChat = ["apple-sys-macos?/BusinessChat", "apple-sys-ios?/BusinessChat"]
CFNetwork = ["apple-sys-macos?/CFNetwork", "apple-sys-ios?/CFNetwork"]
CalendarStore = ["apple-sys-macos?/CalendarStore"]
CallKit = ["apple-sys-macos?/CallKit", "apple-sys-ios?/CallKit"]
CarPlay = ["apple-sys-ios?/CarPlay"]
Carbon = ["apple-sys-macos?/Carbon"]
ClassKit = ["apple-sys-macos?/ClassKit", "apple-sys-ios?/ClassKit"]
ClockKit = ["apple-sys-ios?/ClockKit"]
CloudKit = ["apple-sys-macos?/CloudKit", "apple-sys-ios?/CloudKit"]
Cocoa = ["apple-sys-macos?/Cocoa"]
Collaboration = ["apple-sys-macos?/Collaboration"]
ColorSync = ["apple-sys-macos?/ColorSync", "apple-sys-ios?/ColorSync"]
Contacts = ["apple-sys-macos?/Contacts", "apple-sys-ios?/Contacts"]
ContactsUI = ["apple-sys-macos?/ContactsUI", "apple-sys-ios?/ContactsUI"]
CoreAudio = ["apple-sys-macos?/CoreAudio", "apple-sys-ios?/CoreAudio"]
CoreAudioKit = ["apple-sys-macos?/CoreAudioKit", "apple-sys-ios?/CoreAudioKit"]
CoreBluetooth = ["apple-sys-macos?/CoreBluetooth", "apple-sys-ios?/CoreBluetooth"]
CoreData = ["apple-sys-macos?/CoreData", "apple-sys-ios?/CoreData"]
CoreFoundation = ["apple-sys-macos?/CoreFoundation", "apple-sys-ios?/CoreFoundation"]
CoreGraphics = ["apple-sys-macos?/CoreGraphics", "apple-sys-ios?/CoreGraphics"]
CoreHaptics = ["apple-sys-macos?/CoreHaptics", "apple-sys-ios?/CoreHaptics"]
CoreImage = ["apple-sys-macos?/CoreImage", "apple-sys-ios?/CoreImage"]
CoreLocation = ["apple-sys-macos?/CoreLocation", "apple-sys-ios?/CoreLocation"]
CoreLocationUI = ["apple-sys-ios?/CoreLocationUI"]
CoreMIDI = ["apple-sys-macos?/CoreMIDI", "apple-sys-ios?/CoreMIDI"]
CoreML = ["apple-sys-macos?/CoreML", "apple-sys-ios?/CoreML"]
CoreMedia = ["apple-sys-macos?/CoreMedia", "apple-sys-ios?/CoreMedia"]
CoreMediaIO = ["apple-sys-macos?/CoreMediaIO"]
CoreMotion = ["apple-sys-macos?/CoreMotion", "apple-sys-ios?/CoreMotion"]
CoreNFC = ["apple-sys-ios?/CoreNFC"]
CoreServices = ["apple-sys-macos?/CoreServices", "apple-sys-ios?/CoreServices"]
CoreSpotlight = ["apple-sys-macos?/CoreSpotlight", "apple-sys-ios?/CoreSpotlight"]
CoreTelephony = ["apple-sys-macos?/CoreTelephony", "apple-sys-ios?/CoreTelephony"]
CoreText = ["apple-sys-macos?/CoreText", "apple-sys-ios?/CoreText"]
CoreTransferable = ["apple-sys-macos?/CoreTransferable", "apple-sys-ios?/CoreTransferable"]
CoreVideo = ["apple-sys-macos?/CoreVideo", "apple-sys-ios?/CoreVideo"]
CoreWLAN = ["apple-sys-macos?/CoreWLAN"]
CryptoTokenKit = ["apple-sys-macos?/CryptoTokenKit", "apple-sys-ios?/CryptoTokenKit"]
DVDPlayback = ["apple-sys-macos?/DVDPlayback"]
DataDetection = ["apple-sys-macos?/DataDetection", "apple-sys-ios?/DataDetection"]
DeviceCheck = ["apple-sys-macos?/DeviceCheck", "apple-sys-ios?/DeviceCheck"]
DeviceDiscoveryExtension = ["apple-sys-ios?/DeviceDiscoveryExtension"]
DeviceDiscoveryUI = []
DirectoryService = ["apple-sys-macos?/DirectoryService"]
DiscRecording = ["apple-sys-macos?/DiscRecording"]
DiscRecordingUI = ["apple-sys-macos?/DiscRecordingUI"]
DiskArbitration = ["apple-sys-macos?/DiskArbitration"]
EventKit = ["apple-sys-macos?/EventKit", "apple-sys-ios?/EventKit"]
EventKitUI = ["apple-sys-ios?/EventKitUI"]
ExceptionHandling = ["apple-sys-macos?/ExceptionHandling"]
ExecutionPolicy = ["apple-sys-macos?/ExecutionPolicy"]
ExposureNotification = ["apple-sys-macos?/ExposureNotification", "apple-sys-ios?/ExposureNotification"]
ExtensionFoundation = ["apple-sys-macos?/ExtensionFoundation", "apple-sys-ios?/ExtensionFoundation"]
ExtensionKit = ["apple-sys-macos?/ExtensionKit", "apple-sys-ios?/ExtensionKit"]
ExternalAccessory = ["apple-sys-macos?/ExternalAccessory", "apple-sys-ios?/ExternalAccessory"]
FileProvider = ["apple-sys-macos?/FileProvider", "apple-sys-ios?/FileProvider"]
FileProviderUI = ["apple-sys-macos?/FileProviderUI", "apple-sys-ios?/FileProviderUI"]
FinderSync = ["apple-sys-macos?/FinderSync"]
ForceFeedback = ["apple-sys-macos?/ForceFeedback"]
Foundation = ["apple-sys-macos?/Foundation", "apple-sys-ios?/Foundation"]
GLKit = ["apple-sys-macos?/GLKit", "apple-sys-ios?/GLKit"]
GLUT = ["apple-sys-macos?/GLUT"]
GSS = ["apple-sys-macos?/GSS", "apple-sys-ios?/GSS"]
GameController = ["apple-sys-macos?/GameController", "apple-sys-ios?/GameController"]
GameKit = ["apple-sys-macos?/GameKit", "apple-sys-ios?/GameKit"]
GameplayKit = ["apple-sys-macos?/GameplayKit", "apple-sys-ios?/GameplayKit"]
HealthKit = ["apple-sys-macos?/HealthKit", "apple-sys-ios?/HealthKit"]
HealthKitUI = ["apple-sys-ios?/HealthKitUI"]
HomeKit = ["apple-sys-ios?/HomeKit"]
Hypervisor = ["apple-sys-macos?/Hypervisor"]
ICADevices = ["apple-sys-macos?/ICADevices"]
IMServicePlugIn = ["apple-sys-macos?/IMServicePlugIn"]
IOBluetooth = ["apple-sys-macos?/IOBluetooth"]
IOBluetoothUI = ["apple-sys-macos?/IOBluetoothUI"]
IOKit = ["apple-sys-macos?/IOKit"]
IOSurface = ["apple-sys-macos?/IOSurface", "apple-sys-ios?/IOSurface"]
IOUSBHost = ["apple-sys-macos?/IOUSBHost"]
IdentityLookup = ["apple-sys-macos?/IdentityLookup", "apple-sys-ios?/IdentityLookup"]
IdentityLookupUI = ["apple-sys-ios?/IdentityLookupUI"]
ImageCaptureCore = ["apple-sys-macos?/ImageCaptureCore", "apple-sys-ios?/ImageCaptureCore"]
ImageIO = ["apple-sys-macos?/ImageIO", "apple-sys-ios?/ImageIO"]
InputMethodKit = ["apple-sys-macos?/InputMethodKit"]
InstallerPlugins = ["apple-sys-macos?/InstallerPlugins"]
InstantMessage = ["apple-sys-macos?/InstantMessage"]
Intents = ["apple-sys-macos?/Intents", "apple-sys-ios?/Intents"]
IntentsUI = ["apple-sys-macos?/IntentsUI", "apple-sys-ios?/IntentsUI"]
JavaNativeFoundation = ["apple-sys-macos?/JavaNativeFoundation"]
JavaRuntimeSupport = ["apple-sys-macos?/JavaRuntimeSupport"]
JavaScriptCore = ["apple-sys-macos?/JavaScriptCore", "apple-sys-ios?/JavaScriptCore"]
Kerberos = ["apple-sys-macos?/Kerberos"]
KernelManagement = ["apple-sys-macos?/KernelManagement"]
LDAP = ["apple-sys-macos?/LDAP"]
LatentSemanticMapping = ["apple-sys-macos?/LatentSemanticMapping"]
LinkPresentation = ["apple-sys-macos?/LinkPresentation", "apple-sys-ios?/LinkPresentation"]
LocalAuthentication = ["apple-sys-macos?/LocalAuthentication", "apple-sys-ios?/LocalAuthentication"]
LocalAuthenticationEmbeddedUI = ["apple-sys-macos?/LocalAuthenticationEmbeddedUI", "apple-sys-ios?/LocalAuthenticationEmbeddedUI"]
MLCompute = ["apple-sys-macos?/MLCompute", "apple-sys-ios?/MLCompute"]
MailKit = ["apple-sys-macos?/MailKit"]
MapKit = ["apple-sys-macos?/MapKit", "apple-sys-ios?/MapKit"]
Matter = ["apple-sys-macos?/Matter", "apple-sys-ios?/Matter"]
MatterSupport = ["apple-sys-ios?/MatterSupport"]
MediaAccessibility = ["apple-sys-macos?/MediaAccessibility", "apple-sys-ios?/MediaAccessibility"]
MediaLibrary = ["apple-sys-macos?/MediaLibrary"]
MediaPlayer = ["apple-sys-macos?/MediaPlayer", "apple-sys-ios?/MediaPlayer"]
MediaSetup = ["apple-sys-ios?/MediaSetup"]
MediaToolbox = ["apple-sys-macos?/MediaToolbox", "apple-sys-ios?/MediaToolbox"]
MessageUI = ["apple-sys-ios?/MessageUI"]
Messages = ["apple-sys-ios?/Messages"]
Metal = ["apple-sys-macos?/Metal", "apple-sys-ios?/Metal"]
MetalFX = ["apple-sys-macos?/MetalFX", "apple-sys-ios?/MetalFX"]
MetalKit = ["apple-sys-macos?/MetalKit", "apple-sys-ios?/MetalKit"]
MetalPerformanceShaders = []
MetalPerformanceShadersGraph = []
MetricKit = ["apple-sys-macos?/MetricKit", "apple-sys-ios?/MetricKit"]
MobileCoreServices = ["apple-sys-ios?/MobileCoreServices"]
ModelIO = ["apple-sys-macos?/ModelIO", "apple-sys-ios?/ModelIO"]
MultipeerConnectivity = ["apple-sys-macos?/MultipeerConnectivity", "apple-sys-ios?/MultipeerConnectivity"]
NaturalLanguage = ["apple-sys-macos?/NaturalLanguage", "apple-sys-ios?/NaturalLanguage"]
NearbyInteraction = ["apple-sys-macos?/NearbyInteraction", "apple-sys-ios?/NearbyInteraction"]
NetFS = ["apple-sys-macos?/NetFS"]
Network = ["apple-sys-macos?/Network", "apple-sys-ios?/Network"]
NetworkExtension = ["apple-sys-macos?/NetworkExtension", "apple-sys-ios?/NetworkExtension"]
NewsstandKit = ["apple-sys-ios?/NewsstandKit"]
NotificationCenter = ["apple-sys-macos?/NotificationCenter", "apple-sys-ios?/NotificationCenter"]
OSAKit = ["apple-sys-macos?/OSAKit"]
OSLog = ["apple-sys-macos?/OSLog", "apple-sys-ios?/OSLog"]
OpenAL = ["apple-sys-macos?/OpenAL", "apple-sys-ios?/OpenAL"]
OpenCL = ["apple-sys-macos?/OpenCL"]
OpenDirectory = ["apple-sys-macos?/OpenDirectory"]
OpenGL = ["apple-sys-macos?/OpenGL"]
OpenGLES = ["apple-sys-ios?/OpenGLES"]
PCSC = ["apple-sys-macos?/PCSC"]
PDFKit = ["apple-sys-macos?/PDFKit", "apple-sys-ios?/PDFKit"]
PHASE = ["apple-sys-macos?/PHASE", "apple-sys-ios?/PHASE"]
ParavirtualizedGraphics = ["apple-sys-macos?/ParavirtualizedGraphics"]
PassKit = ["apple-sys-macos?/PassKit", "apple-sys-ios?/PassKit"]
PencilKit = ["apple-sys-macos?/PencilKit", "apple-sys-ios?/PencilKit"]
Photos = ["apple-sys-macos?/Photos", "apple-sys-ios?/Photos"]
PhotosUI = ["apple-sys-macos?/PhotosUI", "apple-sys-ios?/PhotosUI"]
PreferencePanes = ["apple-sys-macos?/PreferencePanes"]
ProximityReader = ["apple-sys-ios?/ProximityReader"]
PushKit = ["apple-sys-macos?/PushKit", "apple-sys-ios?/PushKit"]
PushToTalk = ["apple-sys-macos?/PushToTalk", "apple-sys-ios?/PushToTalk"]
Quartz = ["apple-sys-macos?/Quartz"]
QuartzCore = ["apple-sys-macos?/QuartzCore", "apple-sys-ios?/QuartzCore"]
QuickLook = ["apple-sys-macos?/QuickLook", "apple-sys-ios?/QuickLook"]
QuickLookThumbnailing = ["apple-sys-macos?/QuickLookThumbnailing", "apple-sys-ios?/QuickLookThumbnailing"]
QuickLookUI = ["apple-sys-macos?/QuickLookUI"]
ReplayKit = ["apple-sys-macos?/ReplayKit", "apple-sys-ios?/ReplayKit"]
RoomPlan = ["apple-sys-ios?/RoomPlan"]
SafariServices = ["apple-sys-macos?/SafariServices", "apple-sys-ios?/SafariServices"]
SafetyKit = ["apple-sys-macos?/SafetyKit", "apple-sys-ios?/SafetyKit"]
SceneKit = ["apple-sys-macos?/SceneKit", "apple-sys-ios?/SceneKit"]
ScreenCaptureKit = ["apple-sys-macos?/ScreenCaptureKit"]
ScreenSaver = ["apple-sys-macos?/ScreenSaver"]
ScreenTime = ["apple-sys-macos?/ScreenTime", "apple-sys-ios?/ScreenTime"]
ScriptingBridge = ["apple-sys-macos?/ScriptingBridge"]
Security = ["apple-sys-macos?/Security", "apple-sys-ios?/Security"]
SecurityFoundation = ["apple-sys-macos?/SecurityFoundation"]
SecurityInterface = ["apple-sys-macos?/SecurityInterface"]
SensorKit = ["apple-sys-macos?/SensorKit", "apple-sys-ios?/SensorKit"]
ServiceManagement = ["apple-sys-macos?/ServiceManagement"]
SharedWithYou = ["apple-sys-macos?/SharedWithYou", "apple-sys-ios?/SharedWithYou"]
SharedWithYouCore = ["apple-sys-macos?/SharedWithYouCore", "apple-sys-ios?/SharedWithYouCore"]
ShazamKit = ["apple-sys-macos?/ShazamKit", "apple-sys-ios?/ShazamKit"]
Social = ["apple-sys-macos?/Social", "apple-sys-ios?/Social"]
SoundAnalysis = ["apple-sys-macos?/SoundAnalysis", "apple-sys-ios?/SoundAnalysis"]
Speech = ["apple-sys-macos?/Speech", "apple-sys-ios?/Speech"]
SpriteKit = ["apple-sys-macos?/SpriteKit", "apple-sys-ios?/SpriteKit"]
StoreKit = ["apple-sys-macos?/StoreKit", "apple-sys-ios?/StoreKit"]
SwiftUI = ["apple-sys-macos?/SwiftUI", "apple-sys-ios?/SwiftUI"]
SyncServices = ["apple-sys-macos?/SyncServices"]
SystemConfiguration = ["apple-sys-macos?/SystemConfiguration", "apple-sys-ios?/SystemConfiguration"]
SystemExtensions = ["apple-sys-macos?/SystemExtensions"]
TVMLKit = []
TVServices = []
TVUIKit = []
TWAIN = ["apple-sys-macos?/TWAIN"]
Tcl = ["apple-sys-macos?/Tcl"]
ThreadNetwork = ["apple-sys-macos?/ThreadNetwork", "apple-sys-ios?/ThreadNetwork"]
Twitter = ["apple-sys-ios?/Twitter"]
UIKit = ["apple-sys-ios?/UIKit"]
UniformTypeIdentifiers = ["apple-sys-macos?/UniformTypeIdentifiers", "apple-sys-ios?/UniformTypeIdentifiers"]
UserNotifications = ["apple-sys-macos?/UserNotifications", "apple-sys-ios?/UserNotifications"]
UserNotificationsUI = ["apple-sys-macos?/UserNotificationsUI", "apple-sys-ios?/UserNotificationsUI"]
VideoDecodeAcceleration = ["apple-sys-macos?/VideoDecodeAcceleration"]
VideoSubscriberAccount = ["apple-sys-macos?/VideoSubscriberAccount", "apple-sys-ios?/VideoSubscriberAccount"]
VideoToolbox = ["apple-sys-macos?/VideoToolbox", "apple-sys-ios?/VideoToolbox"]
Virtualization = ["apple-sys-macos?/Virtualization"]
Vision = ["apple-sys-macos?/Vision", "apple-sys-ios?/Vision"]
VisionKit = ["apple-sys-macos?/VisionKit", "apple-sys-ios?/VisionKit"]
WatchConnectivity = ["apple-sys-ios?/WatchConnectivity"]
WatchKit = []
WebKit = ["apple-sys-ios?/WebKit"]
WidgetKit = ["apple-sys-macos?/WidgetKit", "apple-sys-ios?/WidgetKit"]
iAd = ["apple-sys-ios?/iAd"]
iTunesLibrary = ["apple-sys-macos?/iTunesLibrary"]
vmnet = ["apple-sys-macos?/vmnet"]
