//! List audio devices using CoreAudio framework.
//!
//! Queries the audio hardware for all audio devices and prints their names
//! using AudioObjectGetPropertyData.

use apple_sys::CoreAudio::*;
use apple_sys::CoreFoundation::{CFIndex, CFRelease, CFStringGetCString, CFStringRef, CFTypeRef};

// Constants not generated by bindgen (defined as macros in C headers)
const K_AUDIO_OBJECT_SYSTEM_OBJECT: AudioObjectID = 1;
const K_AUDIO_HARDWARE_PROPERTY_DEVICES: AudioObjectPropertySelector = u32::from_be_bytes(*b"dev#");
const K_AUDIO_OBJECT_PROPERTY_SCOPE_GLOBAL: AudioObjectPropertyScope = u32::from_be_bytes(*b"glob");
const K_AUDIO_OBJECT_PROPERTY_ELEMENT_MAIN: AudioObjectPropertyElement = 0;
const K_AUDIO_DEVICE_PROPERTY_DEVICE_NAME_CFSTRING: AudioObjectPropertySelector =
    u32::from_be_bytes(*b"lnam");

fn main() {
    unsafe {
        // Get list of audio device IDs
        let address = AudioObjectPropertyAddress {
            mSelector: K_AUDIO_HARDWARE_PROPERTY_DEVICES,
            mScope: K_AUDIO_OBJECT_PROPERTY_SCOPE_GLOBAL,
            mElement: K_AUDIO_OBJECT_PROPERTY_ELEMENT_MAIN,
        };

        let mut size: u32 = 0;
        let status = AudioObjectGetPropertyDataSize(
            K_AUDIO_OBJECT_SYSTEM_OBJECT,
            &address,
            0,
            std::ptr::null(),
            &mut size,
        );
        if status != 0 {
            eprintln!("AudioObjectGetPropertyDataSize failed: {status}");
            return;
        }

        let device_count = size as usize / std::mem::size_of::<AudioDeviceID>();
        if device_count == 0 {
            println!("No audio devices found");
            return;
        }

        let mut device_ids = vec![0 as AudioDeviceID; device_count];
        let status = AudioObjectGetPropertyData(
            K_AUDIO_OBJECT_SYSTEM_OBJECT,
            &address,
            0,
            std::ptr::null(),
            &mut size,
            device_ids.as_mut_ptr() as *mut std::ffi::c_void,
        );
        if status != 0 {
            eprintln!("AudioObjectGetPropertyData (devices) failed: {status}");
            return;
        }

        println!("Audio Devices:");
        for &device_id in &device_ids {
            // Get device name
            let name_address = AudioObjectPropertyAddress {
                mSelector: K_AUDIO_DEVICE_PROPERTY_DEVICE_NAME_CFSTRING,
                mScope: K_AUDIO_OBJECT_PROPERTY_SCOPE_GLOBAL,
                mElement: K_AUDIO_OBJECT_PROPERTY_ELEMENT_MAIN,
            };

            let mut name_ref: CFStringRef = std::ptr::null();
            let mut name_size = std::mem::size_of::<CFStringRef>() as u32;

            let status = AudioObjectGetPropertyData(
                device_id,
                &name_address,
                0,
                std::ptr::null(),
                &mut name_size,
                &mut name_ref as *mut _ as *mut std::ffi::c_void,
            );

            if status == 0 && !name_ref.is_null() {
                let mut buf = [0u8; 256];
                let ok = CFStringGetCString(
                    name_ref,
                    buf.as_mut_ptr() as *mut i8,
                    buf.len() as CFIndex,
                    0x08000100, // kCFStringEncodingUTF8
                );
                if ok != 0 {
                    let name = std::ffi::CStr::from_ptr(buf.as_ptr() as *const i8);
                    println!("  [{device_id}] {}", name.to_string_lossy());
                }
                CFRelease(name_ref as CFTypeRef);
            }
        }
        println!("Total: {device_count} audio devices");
    }
}
