name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bindgen:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test  --manifest-path=crates/apple-bindgen/Cargo.toml --verbose
    - name: Tool
      run: cargo run --features=bin --manifest-path=crates/apple-bindgen/Cargo.toml --verbose -- generate CoreFoundation --sdk macosx

  sys-macos:
    strategy:
      matrix:
        feature: [
          AVFAudio,
          AVFoundation,
          AVKit,
          AVRouting,
          Accelerate,
          Accessibility,
          Accounts,
          AdServices,
          AdSupport,
          AddressBook,
          AppKit,
          AppTrackingTransparency,
          AppleScriptKit,
          AppleScriptObjC,
          ApplicationServices,
          AudioToolbox,
          AudioUnit,
          AudioVideoBridging,
          AuthenticationServices,
          AutomaticAssessmentConfiguration,
          Automator,
          BackgroundAssets,
          BackgroundTasks,
          BusinessChat,
          CFNetwork,
          CalendarStore,
          CallKit,
          Carbon,
          ClassKit,
          CloudKit,
          Cocoa,
          Collaboration,
          ColorSync,
          Contacts,
          ContactsUI,
          CoreAudio,
          CoreAudioKit,
          CoreBluetooth,
          CoreData,
          CoreFoundation,
          CoreGraphics,
          CoreHaptics,
          CoreImage,
          CoreLocation,
          CoreMIDI,
          CoreML,
          CoreMedia,
          CoreMediaIO,
          CoreMotion,
          CoreServices,
          CoreSpotlight,
          CoreTelephony,
          CoreText,
          CoreVideo,
          CoreWLAN,
          CryptoTokenKit,
          DVDPlayback,
          DataDetection,
          DeviceCheck,
          DirectoryService,
          DiscRecording,
          DiscRecordingUI,
          DiskArbitration,
          EventKit,
          ExceptionHandling,
          ExecutionPolicy,
          ExposureNotification,
          ExtensionKit,
          ExternalAccessory,
          FileProvider,
          FileProviderUI,
          FinderSync,
          ForceFeedback,
          Foundation,
          GLKit,
          GLUT,
          GSS,
          GameController,
          GameKit,
          GameplayKit,
          HealthKit,
          Hypervisor,
          ICADevices,
          IOBluetooth,
          IOBluetoothUI,
          IOKit,
          IOSurface,
          IOUSBHost,
          IdentityLookup,
          ImageCaptureCore,
          ImageIO,
          InputMethodKit,
          InstallerPlugins,
          InstantMessage,
          Intents,
          IntentsUI,
          JavaRuntimeSupport,
          JavaScriptCore,
          Kerberos,
          LatentSemanticMapping,
          LinkPresentation,
          LocalAuthentication,
          LocalAuthenticationEmbeddedUI,
          MLCompute,
          MailKit,
          MapKit,
          Matter,
          MediaAccessibility,
          MediaLibrary,
          MediaPlayer,
          MediaToolbox,
          Metal,
          MetalFX,
          MetalKit,
          # MetalPerformanceShaders,  -- exceed max arg
          # MetalPerformanceShadersGraph,  -- exceed max arg
          MetricKit,
          ModelIO,
          MultipeerConnectivity,
          NaturalLanguage,
          NearbyInteraction,
          NetFS,
          Network,
          NetworkExtension,
          NotificationCenter,
          OSAKit,
          OSLog,
          OpenAL,
          OpenCL,
          OpenDirectory,
          OpenGL,
          PCSC,
          PDFKit,
          PHASE,
          ParavirtualizedGraphics,
          PassKit,
          PencilKit,
          Photos,
          PhotosUI,
          PreferencePanes,
          PushKit,
          Quartz,
          QuartzCore,
          QuickLook,
          QuickLookThumbnailing,
          QuickLookUI,
          ReplayKit,
          SafariServices,
          SafetyKit,
          SceneKit,
          # ScreenCaptureKit,  -- failing on CI env
          ScreenSaver,
          ScreenTime,
          ScriptingBridge,
          Security,
          SecurityFoundation,
          SecurityInterface,
          SensorKit,
          ServiceManagement,
          SharedWithYou,
          SharedWithYouCore,
          ShazamKit,
          Social,
          SoundAnalysis,
          Speech,
          SpriteKit,
          StoreKit,
          SwiftUI,
          SyncServices,
          SystemConfiguration,
          SystemExtensions,
          TWAIN,
          Tcl,
          ThreadNetwork,
          UniformTypeIdentifiers,
          UserNotifications,
          UserNotificationsUI,
          VideoDecodeAcceleration,
          VideoSubscriberAccount,
          VideoToolbox,
          Virtualization,
          Vision,
          VisionKit,
          # WebKit,  -- exceed max arg
          WidgetKit,
          iTunesLibrary,
          vmnet
        ]
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build  --manifest-path=crates/apple-sys/Cargo.toml --verbose --features ${{ matrix.feature }}

  prebuilt-examples:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Build examples
      run: >
        cargo build --manifest-path=crates/apple-sys/Cargo.toml
        --no-default-features
        --features "prebuilt,
        AVFAudio,AVFoundation,AVKit,AVRouting,Accelerate,Accessibility,Accounts,
        AdServices,AdSupport,AddressBook,AppKit,AppTrackingTransparency,AppleScriptKit,
        AppleScriptObjC,ApplicationServices,AudioToolbox,AudioUnit,AudioVideoBridging,
        AuthenticationServices,AutomaticAssessmentConfiguration,Automator,BackgroundAssets,
        BackgroundTasks,BrowserEngineCore,BusinessChat,CFNetwork,CalendarStore,CallKit,
        Carbon,Cinematic,ClassKit,CloudKit,Cocoa,Collaboration,ColorSync,Contacts,
        ContactsUI,CoreAudio,CoreAudioKit,CoreBluetooth,CoreData,CoreFoundation,
        CoreGraphics,CoreHaptics,CoreImage,CoreLocation,CoreMIDI,CoreML,CoreMedia,
        CoreMediaIO,CoreMotion,CoreServices,CoreSpotlight,CoreTelephony,CoreText,
        CoreVideo,CoreWLAN,CryptoTokenKit,DVDPlayback,DataDetection,DeviceCheck,
        DeviceDiscoveryExtension,DirectoryService,DiscRecording,DiscRecordingUI,
        DiskArbitration,EventKit,ExceptionHandling,ExecutionPolicy,ExtensionKit,
        ExternalAccessory,FSKit,FileProvider,FileProviderUI,FinderSync,ForceFeedback,
        Foundation,GLKit,GLUT,GSS,GameController,GameKit,GameSave,GameplayKit,
        HealthKit,Hypervisor,ICADevices,IOBluetooth,IOBluetoothUI,IOKit,IOSurface,
        IOUSBHost,IdentityLookup,ImageCaptureCore,ImageIO,InputMethodKit,InstallerPlugins,
        InstantMessage,Intents,IntentsUI,JavaRuntimeSupport,JavaScriptCore,Kerberos,
        LatentSemanticMapping,LinkPresentation,LocalAuthentication,
        LocalAuthenticationEmbeddedUI,MLCompute,MailKit,MapKit,Matter,MediaAccessibility,
        MediaExtension,MediaLibrary,MediaPlayer,MediaToolbox,Metal,MetalFX,MetalKit,
        MetalPerformanceShaders,MetalPerformanceShadersGraph,MetricKit,ModelIO,
        MultipeerConnectivity,NaturalLanguage,NearbyInteraction,NetFS,Network,
        NetworkExtension,NotificationCenter,OSAKit,OSLog,OpenAL,OpenCL,OpenDirectory,
        OpenGL,PCSC,PDFKit,PHASE,ParavirtualizedGraphics,PassKit,PencilKit,Photos,
        PhotosUI,PreferencePanes,PushKit,Quartz,QuartzCore,QuickLook,QuickLookThumbnailing,
        QuickLookUI,ReplayKit,SafariServices,SafetyKit,SceneKit,
        ScreenSaver,ScreenTime,ScriptingBridge,Security,SecurityFoundation,
        SecurityInterface,SecurityUI,SensitiveContentAnalysis,SensorKit,ServiceManagement,
        SharedWithYou,SharedWithYouCore,ShazamKit,Social,SoundAnalysis,Speech,SpriteKit,
        StoreKit,SwiftUI,Symbols,SyncServices,SystemConfiguration,SystemExtensions,
        TWAIN,Tcl,ThreadNetwork,UniformTypeIdentifiers,UserNotifications,
        UserNotificationsUI,VideoDecodeAcceleration,VideoSubscriberAccount,VideoToolbox,
        Virtualization,Vision,WebKit,WidgetKit,iTunesLibrary,vmnet"
        --examples

  sys-ios:
    strategy:
      matrix:
        feature: [
          ARKit,
          AVFAudio,
          AVFoundation,
          AVKit,
          AVRouting,
          Accelerate,
          Accessibility,
          Accounts,
          AdServices,
          AdSupport,
          AddressBook,
          # AddressBookUI,
          AppClip,
          AppTrackingTransparency,
          AssetsLibrary,
          AudioToolbox,
          AudioUnit,
          AuthenticationServices,
          AutomaticAssessmentConfiguration,
          BackgroundAssets,
          BackgroundTasks,
          BusinessChat,
          CFNetwork,
          CallKit,
          CarPlay,
          ClassKit,
          ClockKit,
          CloudKit,
          ColorSync,
          Contacts,
          ContactsUI,
          CoreAudio,
          CoreAudioKit,
          CoreBluetooth,
          CoreData,
          CoreFoundation,
          CoreGraphics,
          CoreHaptics,
          CoreImage,
          CoreLocation,
          CoreLocationUI,
          CoreMIDI,
          CoreML,
          CoreMedia,
          CoreMotion,
          CoreNFC,
          CoreServices,
          CoreSpotlight,
          CoreTelephony,
          CoreText,
          CoreVideo,
          CryptoTokenKit,
          DataDetection,
          DeviceCheck,
          DeviceDiscoveryExtension,
          EventKit,
          EventKitUI,
          ExposureNotification,
          ExtensionKit,
          ExternalAccessory,
          FileProvider,
          FileProviderUI,
          Foundation,
          GLKit,
          GSS,
          GameController,
          GameKit,
          GameplayKit,
          HealthKit,
          HealthKitUI,
          HomeKit,
          IOSurface,
          IdentityLookup,
          IdentityLookupUI,
          ImageCaptureCore,
          ImageIO,
          Intents,
          IntentsUI,
          JavaScriptCore,
          LinkPresentation,
          LocalAuthentication,
          LocalAuthenticationEmbeddedUI,
          MLCompute,
          MapKit,
          Matter,
          MediaAccessibility,
          MediaPlayer,
          MediaSetup,
          MediaToolbox,
          MessageUI,
          Messages,
          Metal,
          MetalFX,
          MetalKit,
          # MetalPerformanceShaders,
          # MetalPerformanceShadersGraph,
          MetricKit,
          MobileCoreServices,
          ModelIO,
          MultipeerConnectivity,
          NaturalLanguage,
          NearbyInteraction,
          Network,
          NetworkExtension,
          NotificationCenter,
          OSLog,
          OpenAL,
          OpenGLES,
          PDFKit,
          PHASE,
          PassKit,
          PencilKit,
          Photos,
          PhotosUI,
          PushKit,
          PushToTalk,
          QuartzCore,
          QuickLook,
          QuickLookThumbnailing,
          ReplayKit,
          SafariServices,
          SafetyKit,
          SceneKit,
          ScreenTime,
          Security,
          SensorKit,
          SharedWithYou,
          SharedWithYouCore,
          ShazamKit,
          Social,
          SoundAnalysis,
          Speech,
          SpriteKit,
          StoreKit,
          SwiftUI,
          SystemConfiguration,
          ThreadNetwork,
          Twitter,
          UIKit,
          UniformTypeIdentifiers,
          UserNotifications,
          UserNotificationsUI,
          VideoSubscriberAccount,
          VideoToolbox,
          Vision,
          VisionKit,
          WatchConnectivity,
          # WebKit,  -- exceed max arg
          WidgetKit,
          iAd
        ]
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: prepare iOS build
      uses: dtolnay/rust-toolchain@stable
      with:
        target: aarch64-apple-ios
    - name: Build
      run: cargo build --target=aarch64-apple-ios --manifest-path=crates/apple-sys/Cargo.toml --verbose --features ${{ matrix.feature }}
